// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class CSVManager: MonoBehaviour
{
    /*
    public class Row
    {
        public string id;
        public string type;
        public string title;
        public string choice_1;
        public string choice_2;
        public string choice_3;
        public string result_1_id;
        public string result_2_id;
        public string result_3_id;

    }
    public TextAsset File;
    List<Row> rowList = new List<Row>();

    bool isLoaded = false;

    void Start()
    {
        Load(File);
    }


    void Update()
    {
        if (Input.GetKeyDown(KeyCode.A))
        {
            Debug.Log(Find_ID("1").type + "");
        }
    }

    #region CSV Commands
    public List<Row> GetRowList()
    {
        return rowList;

    }

    public bool IsLoaded()
    {
        return isLoaded;
    }
    public void Load(TextAsset csv)
    {
        rowList.Clear();
        string[][] grid = CsvParser2.Parse(csv.text);
        for (int i = 1; i < grid.Length; i++)
        {
            Row row = new Row();
            row.id = grid[i][0];
            row.type = grid[i][1];
            row.title = grid[i][2];
            row.choice_1 = grid[i][3];
            row.choice_2 = grid[i][4];
            row.choice_3 = grid[i][5];
            row.result_1_id = grid[i][6];
            row.result_2_id = grid[i][7];
            row.result_3_id = grid[i][8];

            rowList.Add(row);
        }
        isLoaded = true;
    }

    public int NumRows()
    {
        return rowList.Count;
    }

    public Row GetAt(int i)
    {
        if (rowList.Count <= i)
            return null;
        return rowList[i];
    }

    public Row Find_ID(string find)
    {
        return rowList.Find(x => x.id == find);
    }
    public List<Row> Find_ID_All(string find)
    {
        return rowList.FindAll(x => x.id == find);
    }
    public Row Find_EventID(string find)
    {
        return rowList.Find(x => x.type == find);
    }
    public List<Row> Find_EventID_All(string find)
    {
        return rowList.FindAll(x => x.type == find);
    }
    public Row Find_Title(string find)
    {
        return rowList.Find(x => x.title == find);
    }
    public List<Row> Find_Title_All(string find)
    {
        return rowList.FindAll(x => x.title == find);
    }
    public Row Find_Choice_1(string find)
    {
        return rowList.Find(x => x.choice_1 == find);
    }
    public List<Row> Find_Choice_1_All(string find)
    {
        return rowList.FindAll(x => x.choice_1 == find);
    }
    public Row Find_Choice_2(string find)
    {
        return rowList.Find(x => x.choice_2 == find);
    }
    public List<Row> Find_Choice_2_All(string find)
    {
        return rowList.FindAll(x => x.choice_2 == find);
    }
    public Row Find_Choice_3(string find)
    {
        return rowList.Find(x => x.choice_3 == find);
    }
    public List<Row> Find_Choice_3_All(string find)
    {
        return rowList.FindAll(x => x.choice_3 == find);
    }

    public Row Find_Result_1(string find)
    {
        return rowList.Find(x => x.result_1_id == find);
    }
    public List<Row> Find_Result_1_All(string find)
    {
        return rowList.FindAll(x => x.result_1_id == find);
    }
    public Row Find_Result_2(string find)
    {
        return rowList.Find(x => x.result_2_id == find);
    }
    public List<Row> Find_Result_2_All(string find)
    {
        return rowList.FindAll(x => x.result_2_id == find);
    }
    public Row Find_Result_3(string find)
    {
        return rowList.Find(x => x.result_3_id == find);
    }
    public List<Row> Find_Result_3_All(string find)
    {
        return rowList.FindAll(x => x.result_3_id == find);
    }
#endregion*/
}