// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class CSVManager: AManager<CSVManager>
{
    
    public class Row
    {
        public string id;
        public string title;
        public string content;
        public string choice_1;
        public string choice_2;
        public string result_1;
        public string result_2;
        public string effect_1;
        public string effect_2;
    }
    public TextAsset File;
    public List<Row> rowList = new List<Row>();

    bool isLoaded = false;

    void Start()
    {
        Load(File);
    }


    void Update()
    {
        if (Input.GetKeyDown(KeyCode.A))
        {
            Debug.Log(Find_ID(1).content + "");
        }
    }

    #region CSV Commands
    public List<Row> GetRowList()
    {
        return rowList;
    }

    public bool IsLoaded()
    {
        return isLoaded;
    }
    public void Load(TextAsset csv)
    {
        rowList.Clear();
        string[][] grid = CsvParser2.Parse(csv.text);
        for (int i = 1; i < grid.Length; i++)
        {
            Row row = new Row();
            row.id = grid[i][0];
            row.title = grid[i][1];
            row.content = grid[i][2];
            row.choice_1 = grid[i][3];
            row.choice_2 = grid[i][4];
            row.result_1 = grid[i][5];
            row.result_2 = grid[i][6];
            row.effect_1 = grid[i][7];
            row.effect_2 = grid[i][8];
            rowList.Add(row);
        }
        isLoaded = true;
    }

    public int NumRows()
    {
        return rowList.Count;
    }

    public Row GetAt(int i)
    {
        if (rowList.Count <= i)
            return null;
        return rowList[i];
    }

    public Row Find_ID(int find)
    {
        return rowList.Find(x => x.id == find.ToString());
    }
    public List<Row> Find_ID_All(string find)
    {
        return rowList.FindAll(x => x.id == find);
    }
    public Row Find_Title(string find)
    {
        return rowList.Find(x => x.title == find);
    }
    public List<Row> Find_Title_All(string find)
    {
        return rowList.FindAll(x => x.title == find);
    }
    public Row Find_Content(string find)
    {
        return rowList.Find(x => x.content == find);
    }
    public List<Row> Find_Content_All(string find)
    {
        return rowList.FindAll(x => x.content == find);
    }
    public Row Find_Choice_1(string find)
    {
        return rowList.Find(x => x.choice_1 == find);
    }
    public List<Row> Find_Choice_1_All(string find)
    {
        return rowList.FindAll(x => x.choice_1 == find);
    }
    public Row Find_Choice_2(string find)
    {
        return rowList.Find(x => x.choice_2 == find);
    }
    public List<Row> Find_Choice_2_All(string find)
    {
        return rowList.FindAll(x => x.choice_2 == find);
    }

    public Row Find_Result_1(string find)
    {
        return rowList.Find(x => x.result_1 == find);
    }
    public List<Row> Find_Result_1_All(string find)
    {
        return rowList.FindAll(x => x.result_1 == find);
    }
    public Row Find_Result_2(string find)
    {
        return rowList.Find(x => x.result_2 == find);
    }
    public List<Row> Find_Result_2_All(string find)
    {
        return rowList.FindAll(x => x.result_2 == find);
    }
    public Row Find_Result_3(string find)
    {
        return rowList.Find(x => x.effect_1 == find);
    }
    public List<Row> Find_Result_3_All(string find)
    {
        return rowList.FindAll(x => x.effect_1 == find);
    }
    public Row Find_Effect(string find)
    {
        return rowList.Find(x => x.effect_2 == find);
    }
    public List<Row> Find_Effect_All(string find)
    {
        return rowList.FindAll(x => x.effect_2 == find);
    }
    #endregion
}